# Generated by Django 4.0.3 on 2024-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_serverstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
