# Generated by Django 4.0.3 on 2024-05-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_alter_serverstatus_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=40)),
                ('last_update', models.DateField()),
            ],
        ),
    ]
