# Generated by Django 4.0.3 on 2024-05-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerStatus',
        ),
    ]
