# Generated by Django 4.0.3 on 2024-05-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_delete_serverstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serverstatus',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('server_id', models.TextField()),
                ('temperature', models.TextField()),
                ('humidity', models.TextField()),
                ('reg_date', models.DateField()),
                ('tempAVG', models.TextField()),
                ('humiAVG', models.TextField()),
            ],
        ),
    ]
