# Generated by Django 4.0.3 on 2024-05-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_serverstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='reg_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='temperature',
            field=models.CharField(max_length=5),
        ),
    ]
